name: Build ESP32 Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up ESP-IDF
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh esp32
        echo "source $GITHUB_WORKSPACE/esp-idf/export.sh" >> $GITHUB_ENV

    - name: Build firmware
      run: |
        source $GITHUB_WORKSPACE/esp-idf/export.sh
        idf.py set-target esp32
        idf.py build

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: yoradio-esp32-firmware
        path: build/*.bin
